name: gestion_hospitalaria
description: modelo final para el diplomado web y movil.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ">=6.1.2 <7.0.0"
  shared_preferences: ">=2.3.3 <3.0.0"
  supabase_flutter: ">=2.15.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <7.0.0"
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "iconos/equipo-medico.png"

flutter:
  uses-material-design: true
  assets:
    - iconos/equipo-medico.png