typedef Json = Map<String, dynamic>;

String? _text(dynamic value) => value?.toString();
DateTime? _date(dynamic value) => value == null ? null : DateTime.tryParse(value.toString());

abstract class SupabaseModel {
  const SupabaseModel();
  Json toMap();
}

class Administrador extends SupabaseModel {
  const Administrador({this.id, this.userId, this.nombre, this.apellido, this.email, this.estado = 'activo'});
  final String? id, userId, nombre, apellido, email;
  final String estado;
  factory Administrador.fromMap(Json m) => Administrador(id: _text(m['id']), userId: _text(m['user_id']), nombre: _text(m['nombre']), apellido: _text(m['apellido']), email: _text(m['email']), estado: _text(m['estado']) ?? 'activo');
  @override Json toMap() => {'user_id': userId, 'nombre': nombre, 'apellido': apellido, 'email': email, 'estado': estado}..removeWhere((k, v) => v == null);
  String get nombreCompleto => [nombre, apellido].whereType<String>().join(' ');
}

class Especialidad extends SupabaseModel {
  const Especialidad({this.id, required this.nombre, this.descripcion, this.estado = 'activo'});
  final String? id, descripcion; final String nombre, estado;
  factory Especialidad.fromMap(Json m) => Especialidad(id: _text(m['id']), nombre: _text(m['nombre']) ?? '', descripcion: _text(m['descripcion']), estado: _text(m['estado']) ?? 'activo');
  @override Json toMap() => {'nombre': nombre, 'descripcion': descripcion, 'estado': estado};
}

class Personal extends SupabaseModel {
  const Personal({this.id, required this.codigo, required this.nombre, required this.apellido, required this.ci, this.sexo, this.telefono, required this.tipoPersonal, this.estado = 'activo'});
  final String? id, sexo, telefono; final String codigo, nombre, apellido, ci, tipoPersonal, estado;
  factory Personal.fromMap(Json m) => Personal(id: _text(m['id']), codigo: _text(m['codigo']) ?? '', nombre: _text(m['nombre']) ?? '', apellido: _text(m['apellido']) ?? '', ci: _text(m['ci']) ?? '', sexo: _text(m['sexo']), telefono: _text(m['telefono']), tipoPersonal: _text(m['tipo_personal']) ?? '', estado: _text(m['estado']) ?? 'activo');
  @override Json toMap() => {'codigo': codigo, 'nombre': nombre, 'apellido': apellido, 'ci': ci, 'sexo': sexo, 'telefono': telefono, 'tipo_personal': tipoPersonal, 'estado': estado};
  String get nombreCompleto => '$nombre $apellido';
}

class Medico extends SupabaseModel { const Medico({this.id, required this.personalId, this.especialidadId, this.matriculaProfesional}); final String? id, especialidadId, matriculaProfesional; final String personalId; factory Medico.fromMap(Json m) => Medico(id: _text(m['id']), personalId: _text(m['personal_id']) ?? '', especialidadId: _text(m['especialidad_id']), matriculaProfesional: _text(m['matricula_profesional'])); @override Json toMap() => {'personal_id': personalId, 'especialidad_id': especialidadId, 'matricula_profesional': matriculaProfesional}; }
class Enfermero extends SupabaseModel { const Enfermero({this.id, required this.personalId, this.especialidadId, this.codigoEnfermero}); final String? id, especialidadId, codigoEnfermero; final String personalId; factory Enfermero.fromMap(Json m) => Enfermero(id: _text(m['id']), personalId: _text(m['personal_id']) ?? '', especialidadId: _text(m['especialidad_id']), codigoEnfermero: _text(m['codigo_enfermero'])); @override Json toMap() => {'personal_id': personalId, 'especialidad_id': especialidadId, 'codigo_enfermero': codigoEnfermero}; }
class Pasante extends SupabaseModel { const Pasante({this.id, required this.personalId, this.supervisorPersonalId, this.universidad, this.carrera, this.areaPractica, this.fechaInicio, this.fechaFin}); final String? id, supervisorPersonalId, universidad, carrera, areaPractica; final DateTime? fechaInicio, fechaFin; final String personalId; factory Pasante.fromMap(Json m) => Pasante(id: _text(m['id']), personalId: _text(m['personal_id']) ?? '', supervisorPersonalId: _text(m['supervisor_personal_id']), universidad: _text(m['universidad']), carrera: _text(m['carrera']), areaPractica: _text(m['area_practica']), fechaInicio: _date(m['fecha_inicio']), fechaFin: _date(m['fecha_fin'])); @override Json toMap() => {'personal_id': personalId, 'supervisor_personal_id': supervisorPersonalId, 'universidad': universidad, 'carrera': carrera, 'area_practica': areaPractica, 'fecha_inicio': fechaInicio?.toIso8601String().substring(0, 10), 'fecha_fin': fechaFin?.toIso8601String().substring(0, 10)}; }
class PersonalDiaTrabajo extends SupabaseModel { const PersonalDiaTrabajo({this.id, required this.personalId, required this.diaSemana, required this.horaInicio, required this.horaFin}); final String? id; final String personalId, diaSemana, horaInicio, horaFin; factory PersonalDiaTrabajo.fromMap(Json m) => PersonalDiaTrabajo(id: _text(m['id']), personalId: _text(m['personal_id']) ?? '', diaSemana: _text(m['dia_semana']) ?? '', horaInicio: _text(m['hora_inicio']) ?? '', horaFin: _text(m['hora_fin']) ?? ''); @override Json toMap() => {'personal_id': personalId, 'dia_semana': diaSemana, 'hora_inicio': horaInicio, 'hora_fin': horaFin}; }
class Turno extends SupabaseModel { const Turno({this.id, required this.fecha, required this.tipo, required this.horaInicio, required this.horaFin, required this.area, this.estado = 'programado', this.observaciones}); final String? id, observaciones; final DateTime fecha; final String tipo, horaInicio, horaFin, area, estado; factory Turno.fromMap(Json m) => Turno(id: _text(m['id']), fecha: _date(m['fecha']) ?? DateTime.now(), tipo: _text(m['tipo']) ?? '', horaInicio: _text(m['hora_inicio']) ?? '', horaFin: _text(m['hora_fin']) ?? '', area: _text(m['area']) ?? '', estado: _text(m['estado']) ?? 'programado', observaciones: _text(m['observaciones'])); @override Json toMap() => {'fecha': fecha.toIso8601String().substring(0,10), 'tipo': tipo, 'hora_inicio': horaInicio, 'hora_fin': horaFin, 'area': area, 'estado': estado, 'observaciones': observaciones}; }
class AsignacionTurno extends SupabaseModel { const AsignacionTurno({this.id, required this.turnoId, required this.personalId, required this.rolTurno, this.observaciones}); final String? id, observaciones; final String turnoId, personalId, rolTurno; factory AsignacionTurno.fromMap(Json m) => AsignacionTurno(id: _text(m['id']), turnoId: _text(m['turno_id']) ?? '', personalId: _text(m['personal_id']) ?? '', rolTurno: _text(m['rol_turno']) ?? '', observaciones: _text(m['observaciones'])); @override Json toMap() => {'turno_id': turnoId, 'personal_id': personalId, 'rol_turno': rolTurno, 'observaciones': observaciones}; }
class Emergencia extends SupabaseModel { const Emergencia({this.id, required this.codigo, required this.fecha, required this.hora, required this.area, required this.tipo, required this.prioridad, required this.descripcion, this.estado = 'pendiente'}); final String? id; final String codigo, hora, area, tipo, prioridad, descripcion, estado; final DateTime fecha; factory Emergencia.fromMap(Json m) => Emergencia(id: _text(m['id']), codigo: _text(m['codigo']) ?? '', fecha: _date(m['fecha']) ?? DateTime.now(), hora: _text(m['hora']) ?? '', area: _text(m['area']) ?? '', tipo: _text(m['tipo']) ?? '', prioridad: _text(m['prioridad']) ?? '', descripcion: _text(m['descripcion']) ?? '', estado: _text(m['estado']) ?? 'pendiente'); @override Json toMap() => {'codigo': codigo, 'fecha': fecha.toIso8601String().substring(0,10), 'hora': hora, 'area': area, 'tipo': tipo, 'prioridad': prioridad, 'descripcion': descripcion, 'estado': estado}; }
class EquipoEmergencia extends SupabaseModel { const EquipoEmergencia({this.id, required this.emergenciaId, this.nombre}); final String? id, nombre; final String emergenciaId; factory EquipoEmergencia.fromMap(Json m) => EquipoEmergencia(id: _text(m['id']), emergenciaId: _text(m['emergencia_id']) ?? '', nombre: _text(m['nombre'])); @override Json toMap() => {'emergencia_id': emergenciaId, 'nombre': nombre}; }
class EquipoEmergenciaPersonal extends SupabaseModel { const EquipoEmergenciaPersonal({this.id, required this.equipoId, required this.personalId, required this.rol, this.esResponsable = false}); final String? id; final String equipoId, personalId, rol; final bool esResponsable; factory EquipoEmergenciaPersonal.fromMap(Json m) => EquipoEmergenciaPersonal(id: _text(m['id']), equipoId: _text(m['equipo_id']) ?? '', personalId: _text(m['personal_id']) ?? '', rol: _text(m['rol']) ?? '', esResponsable: m['es_responsable'] == true); @override Json toMap() => {'equipo_id': equipoId, 'personal_id': personalId, 'rol': rol, 'es_responsable': esResponsable}; }
class Auditoria extends SupabaseModel { const Auditoria({this.id, this.administradorId, this.accion, this.tabla, this.registroId, this.descripcion, this.fecha}); final String? id, administradorId, accion, tabla, registroId, descripcion; final DateTime? fecha; factory Auditoria.fromMap(Json m) => Auditoria(id: _text(m['id']), administradorId: _text(m['administrador_id']), accion: _text(m['accion']), tabla: _text(m['tabla']), registroId: _text(m['registro_id']), descripcion: _text(m['descripcion']), fecha: _date(m['created_at'] ?? m['fecha'])); @override Json toMap() => {'administrador_id': administradorId, 'accion': accion, 'tabla': tabla, 'registro_id': registroId, 'descripcion': descripcion}; }
